Repository githedgehog/dataplane, pull requests merged in 2025-02, with the labels that each got.

#198 .gitignore: Add artifact directory
  .gitignore
Labels: clean-up

#203 Bump to dpdk with virtio / AF_PACKET support
  scripts/dpdk-sys.env
Labels: update

#210 Use workspace feature rather than individual versions
  Cargo.lock
  dpdk-sys/Cargo.toml
Labels: enhancement, dependencies

#209 Remove syn exception in deny.toml
  deny.toml
Labels: dependencies

#212 Prep for 2024 edition
  Cargo.lock
  net/src/tcp/port.rs
  net/src/udp/port.rs
Labels: enhancement, update

#228 ci: Fix concurrency group for merge queue
  .github/workflows/dev.yml
  .github/workflows/docs.yml
  .github/workflows/lint-cargo-fmt.yml
  .github/workflows/sterile.yml
Labels: ci

#229 Add CI check for SPDX/copyright headers
  .github/workflows/lint-license-headers.yml
Labels: ci

#225 Reorganise NAT elements, main() function
  dataplane/src/main.rs
Labels: area/nat

#262 ci: Add linter for making sure we follow the Conventional Commits spec
  .github/workflows/lint-commitlint.yml
Labels: ci

#263 ci: Fix concurrency group for license/headers check workflow
  .github/workflows/lint-license-headers.yml
Labels: ci

#264 ci: Fix typo, remove verbose mode in commitlint linter workflow
  .github/workflows/lint-commitlint.yml
Labels: ci

#273 Use documented version of free
  dpdk/src/mem.rs
Labels: clean-up

#268 build: fix incorrect commit message in bump.yml
  .github/workflows/bump.yml
Labels: ci, clean-up

#272 fix: remove unused cargo alias commands
  .cargo/config.toml
Labels: bug, clean-up

#267 Remove musl support
  .github/workflows/dev.yml
  .github/workflows/sterile.yml
  README.md
  design-docs/src/mdbook/src/build/compile-env.md
  design-docs/src/mdbook/src/build/fake-nix.md
  design-docs/src/mdbook/src/build/index.md
Labels: dependencies

#275 refactor: remove nextest.toml
  .config/nextest.toml
Labels: clean-up

#274 Minor improvements to dependabot
  .github/dependabot.yml
Labels: enhancement, dependencies, ci

#281 bump: Fix Dependabot's commits title message
  .github/dependabot.yml
Labels: dependencies, clean-up

#283 bump(cargo): manual bump
  Cargo.lock
Labels: dependencies

#287 Fix dependabot major version update
  .github/dependabot.yml
Labels: enhancement

#310 ci: Disable "cargo clippy" with Nightly toolchain in dev workflow
  .github/workflows/dev.yml
Labels: ci
