Repository githedgehog/dataplane, pull requests merged in 2025-04, with the labels that each got.

#399 ci: Fixes for "bump" workflow
  .github/workflows/bump.yml
Labels: ci

#400 docs(README.md): Fix Rust version requirement
  README.md
Labels: documentation

#403 fix(net): serde should not be optional
  dataplane/Cargo.toml
  net/Cargo.toml
  net/src/eth/ethtype.rs
  net/src/eth/mac.rs
  net/src/interface/mod.rs
  net/src/ipv4/addr.rs
  net/src/ipv6/flow_label.rs
  net/src/tcp/checksum.rs
  net/src/tcp/port.rs
  net/src/udp/checksum.rs
  net/src/udp/port.rs
  net/src/vlan/mod.rs
  net/src/vxlan/mod.rs
  net/src/vxlan/vni.rs
Labels: clean-up

#402 fix: rework id crate
  id/src/lib.rs
Labels: enhancement

#412 Test runner
  .cargo/config.toml
  dev-env-template/etc.template/group.template
  justfile
  net/src/packet/hash.rs
  scripts/dpdk-sys.env
  scripts/test-runner.sh
Labels: enhancement

#413 feat: add back nextest config
  .config/nextest.toml
Labels: enhancement
