Repository githedgehog/dataplane, pull requests merged in 2025-09, with the labels that each got.

#818 NAT: allocator tests clean-up (v2)
  nat/src/stateful/apalloc/test_alloc.rs
Labels: clean-up, area/nat

#826 chore(pkt-meta, flow-info): Split out flow-info into its own crate
  Cargo.lock
  Cargo.toml
  flow-info/Cargo.toml
  flow-info/src/atomic_instant.rs
  flow-info/src/flow_info.rs
  flow-info/src/flow_info_item.rs
  flow-info/src/lib.rs
  pkt-meta/Cargo.toml
  pkt-meta/src/flow_table/mod.rs
  pkt-meta/src/flow_table/table.rs
Labels: ci:+vlab

#863 ci: Install cargo-binstall from dedicated Action
  .github/workflows/bump.yml
Labels: ci

#864 Batch read packets in kernel worker threads
  dataplane/src/drivers/kernel.rs
Labels: ci:+vlab

#865 fix(dataplane): Validate num workers to be in range(1..=64)
  dataplane/src/args.rs
Labels: ci:+vlab

#873 ci: Fix image tag for cargo-binstall
  .github/workflows/bump.yml
Labels: ci
