Repository githedgehog/dataplane, pull requests merged in 2025-01, with the labels that each got.

#150 ci: Fix step condition, to fix docs publishing
  .github/workflows/docs.yml
Labels: ci

#148 ci: Fix bump.yml by calling the right script
  .github/workflows/bump.yml
Labels: ci

#156 [RFC] justfile: Remove references to dev-env container
  .github/workflows/sterile.yml
  justfile
Labels: clean-up

#164 Bump to new DPDK bindings
  Cargo.lock
  dpdk-sys/Cargo.toml
  dpdk-sys/build.rs
  dpdk/src/dev.rs
  dpdk/src/eal.rs
  dpdk/src/mem.rs
  dpdk/src/queue/rx.rs
  scratch/src/main.rs
  scripts/dpdk-sys.env
Labels: dependencies, update

#186 docs: Add notes on repositories architecture
  design-docs/src/mdbook/src/build/index.md
Labels: documentation
